project:
  type: website

lang: hu
language:
  toc-title-website: "Ezen az oldalon"
  title-block-author-single: "SZERZŐ"
  title-block-author-plural: "SZERZŐK"
  title-block-published: "KÖZZÉTÉVE"
  listing-page-order-by: "Rendezés"
  listing-page-order-by-default: "Alapértelmezett"
  listing-page-order-by-date-asc: "Legrégebbi elöl"
  listing-page-order-by-date-desc: "Legújabb elöl"
  listing-page-filter: "Szűrés"
  listing-page-field-date: "Dátum"
  listing-page-field-title: "Cím"
  listing-page-field-author: "Szerző"
  back-to-top: "Vissza az oldal tetejére"

output-dir: _site

website:
  title: "Ember--MI"
  bread-crumbs: true
  back-to-top-navigation: true
  sidebar:
    background: light
    search: true
    contents:
      - text: "Kezdőlap"
        href: index.qmd
      - text: "Kutatócsoportról"
        href: kutatocsoportrol.qmd
      - text: "MI eszközök"
        href: mi_eszkozok_iras.qmd
      - section: "MI hírek"
        contents: 
          - text: "Napi MI hírek"
            href: lp_mi_hirek_napi.qmd
          - text: "Heti MI-Pszicho hírek"
            href: lp_mi_hirek_heti_pszicho.qmd
        

  page-footer:
    background: light
    left: "Copyright 2026. Ember--MI Kutatócsoport, DE Pszichológiai Intézet" 

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    respect-user-color-scheme: true
    css: styles.css
    toc: true
                
