---
title: "Üdvözöljük az Ember--MI kutatócsoport honlapján"
---


Az Ember–MI Kutatócsoport célja annak tudományos vizsgálata, hogy a mesterséges intelligencia miként alakítja az emberi gondolkodást, döntéshozatalt, munkavégzést és társadalmi kapcsolatokat. Interdiszciplináris megközelítésünkben a technológiai fejlődést emberközpontú, etikai és társadalmi szempontokkal kapcsoljuk össze.

Kutatócsoportunk a mesterséges intelligencia felelős, átlátható és társadalmilag hasznos alkalmazását kívánja elősegíteni. Tudományos munkánkkal hozzájárulunk ahhoz, hogy az új technológiák fejlesztése és használata az emberi értékek, jogok és szükségletek figyelembevételével történjen.

## Kutatási területeink

* ember–MI együttműködés és interakció;
* a mesterséges intelligencia társadalmi és kulturális hatásai;
* etikus és felelős MI-fejlesztés;
* bizalom, átláthatóság és elszámoltathatóság;
* a mesterséges intelligencia szerepe az oktatásban és a munka világában;
* emberközpontú technológiai megoldások vizsgálata.

## Tevékenységünk

A kutatócsoport elméleti és empirikus kutatásokat végez, szakmai rendezvényeket szervez, valamint hazai és nemzetközi együttműködésekben vesz részt. Eredményeinket tudományos publikációk, konferencia-előadások és közérthető szakmai anyagok formájában tesszük hozzáférhetővé.

## Együttműködés

Nyitottak vagyunk kutatási, oktatási és szakmai együttműködésekre felsőoktatási intézményekkel, kutatóhelyekkel, közintézményekkel, civil szervezetekkel és vállalati partnerekkel.

## Kapcsolat

Kutatási együttműködéssel, szakmai megkereséssel vagy rendezvényeinkkel kapcsolatban forduljon hozzánk bizalommal.

- E-mail: hujber-mitru.szilvia@arts.unideb.hu
